Repository CA-G12/E-commerce-Team1-, pull requests merged in 2022-07, with the labels that each got.

#20 1 create file structure
  css/cart.css
  css/index.css
  css/products.css
  css/seller.css
  html/cart.html
  html/products.html
  html/seller.html
  images/all-product.png
  images/emptyCart.png
  index.html
  js/cart.js
  js/products.js
  js/seller.js
Labels: Approved

#21 Create landing page and style it and copy header and footer for every page
  css/cart.css
  css/index.css
  css/products.css
  css/seller.css
  html/cart.html
  html/products.html
  html/seller.html
  images/Planty's Logo.png
  images/landingPage.PNG
  index.html
Labels: Approved

#22 create products page and style it (this page displays products page and you can add to cart)
  css/products.css
  html/products.html
Labels: Approved

#23 this function displays products from localstarge
  js/products.js
Labels: Approved

#24 create function add to Cart
  js/products.js
Labels: Merged

#25 Create Search function for products page
  js/products.js
Labels: Approved

#26 create cart structure and style
  css/cart.css
  html/cart.html
Labels: Approved

#27 added the purchases display function to the cart
  js/cart.js
Labels: Awaiting-review

#28 Seller page html and css
  css/seller.css
  html/seller.html
Labels: Approved

#29 created function to calculate total price for purchases in cart
  js/cart.js
Labels: Approved

#30 created a delete function to handle purchases in the cart
  js/cart.js
Labels: Awaiting-review

#31 Add product
  js/seller.js
Labels: Approved

#32 Showing items
  js/seller.js
Labels: Approved

#33 Add search function
  html/seller.html
  js/seller.js
Labels: Awaiting-review

#34 seler delete function
  js/seller.js
Labels: Approved

#36 fixing some links
  html/cart.html
  html/seller.html
  js/cart.js
Labels: Awaiting-review

#42 fixing seller page
  html/seller.html
  js/functions.js
  js/seller.js
Labels: Awaiting-review

#44 delete comments
  html/cart.html
  html/seller.html
  js/cart.js
  js/products.js
  js/seller.js
Labels: Approved
